<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.5

$CONF['sql_user']=htmlspecialchars_decode('');
$CONF['sql_host']=htmlspecialchars_decode('localhost');
$CONF['sql_db']=htmlspecialchars_decode('');
$CONF['ftp_use']=htmlspecialchars_decode('0');
$CONF['email_use']=htmlspecialchars_decode('1');
$CONF['sitename']=htmlspecialchars_decode('example.com');
$CONF['lang']=htmlspecialchars_decode('english');
$CONF['import_error']=htmlspecialchars_decode('1');
$CONF['no_login']=htmlspecialchars_decode('0');
$CONF['login']=htmlspecialchars_decode('0');
$CONF['dir_backup']=htmlspecialchars_decode('0');
$CONF['dir_rec']=htmlspecialchars_decode('1');
$CONF['email']=htmlspecialchars_decode('mail@example.com');
$CONF['ftp_pasv']=htmlspecialchars_decode('1');
$CONF['ftp_del']=htmlspecialchars_decode('1');
$CONF['ftp_server']=htmlspecialchars_decode('example.com');
$CONF['ftp_user']=htmlspecialchars_decode('');
$CONF['ftp_port']=htmlspecialchars_decode('21');
$CONF['date']=htmlspecialchars_decode('%d.%m.%Y %H:%M Uhr');
$CONF['del_time']=htmlspecialchars_decode('3');
$CONF['del_number']=htmlspecialchars_decode('5');
$CONF['timelimit']=htmlspecialchars_decode('30');
$CONF['confirm']=htmlspecialchars_decode('1');
$CONF['stylesheet']=htmlspecialchars_decode('standard');
$CONF['ftp_path']=htmlspecialchars_decode('');
$CONF['ftp_passwd']=htmlspecialchars_decode('');
$CONF['sql_passwd']=htmlspecialchars_decode('');

?>